SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/08/2018 
09:44:42.055849".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/08/2018 
09:44:42.641648".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/08/2018 
09:44:42.644211".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/08/2018 
09:44:43.023508".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
12:19:39.050743".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/26/2018 
12:19:39.546233".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/26/2018 
12:19:39.548735".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/26/2018 
12:19:39.665282".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
16:20:35.466758".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/26/2018 
16:20:35.978496".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/26/2018 
16:20:35.980753".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/26/2018 
16:20:36.154612".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/01/2018 
13:37:49.295809".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/01/2018 
13:37:49.975154".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/01/2018 
13:37:49.978240".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/01/2018 
13:37:50.286934".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
16:44:32.978082".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
16:44:33.766422".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
16:44:33.773386".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
16:44:34.004858".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:48:11.483084".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
20:48:12.271909".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
20:48:12.274812".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
20:48:12.481318".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

