SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/08/2018 
09:44:40.770082".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/08/2018 
09:44:41.528379".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/08/2018 
09:44:41.530312".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/08/2018 
09:44:41.775591".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
12:19:38.018764".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/26/2018 
12:19:38.628525".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/26/2018 
12:19:38.630894".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/26/2018 
12:19:38.846323".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
16:20:34.386127".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/26/2018 
16:20:34.941738".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/26/2018 
16:20:34.948132".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/26/2018 
16:20:35.238574".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/01/2018 
13:37:47.921709".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/01/2018 
13:37:48.698951".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/01/2018 
13:37:48.706734".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/01/2018 
13:37:49.037052".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
16:44:31.249397".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
16:44:32.412831".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
16:44:32.419777".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
16:44:32.820566".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:48:10.069216".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
20:48:11.064939".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
20:48:11.068100".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
20:48:11.386717".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

