SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/05/2018 
06:15:43.020282".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/05/2018 
06:15:43.658869".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/05/2018 
06:15:43.661698".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/05/2018 
06:15:44.030378".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/01/2018 
07:42:13.328738".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/01/2018 
07:42:14.332162".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/01/2018 
07:42:14.335862".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/01/2018 
07:42:14.662140".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/24/2020 
17:18:09.639132".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/24/2020 
17:18:10.073057".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/24/2020 
17:18:10.076335".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/24/2020 
17:18:10.275630".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:23:15.226999".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
20:23:16.107856".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
20:23:16.111088".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
20:23:16.419766".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

