SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/teller.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/05/2018 
06:15:44.325287".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "1000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "1000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/05/2018 
06:15:44.450853".


Number of rows read         = 1000
Number of rows skipped      = 0
Number of rows loaded       = 1000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 1000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/teller.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/01/2018 
07:42:14.996063".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "1000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "1000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/01/2018 
07:42:15.129333".


Number of rows read         = 1000
Number of rows skipped      = 0
Number of rows loaded       = 1000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 1000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/teller.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/24/2020 
17:18:10.392351".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "1000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "1000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/24/2020 
17:18:10.435574".


Number of rows read         = 1000
Number of rows skipped      = 0
Number of rows loaded       = 1000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 1000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/teller.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:23:16.563202".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "1000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "1000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
20:23:16.617846".


Number of rows read         = 1000
Number of rows skipped      = 0
Number of rows loaded       = 1000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 1000

