SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/05/2018 
06:15:41.401598".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/05/2018 
06:15:42.272717".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/05/2018 
06:15:42.276896".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/05/2018 
06:15:42.638724".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/01/2018 
07:42:11.416874".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/01/2018 
07:42:12.405507".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/01/2018 
07:42:12.408031".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/01/2018 
07:42:12.938170".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/24/2020 
17:18:08.786648".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/24/2020 
17:18:09.288379".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/24/2020 
17:18:09.291405".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/24/2020 
17:18:09.487147".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/monitor/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:23:13.783673".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
20:23:14.774681".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
20:23:14.777902".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
20:23:15.088256".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

