SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/08/2018 
10:45:38.415469".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL3531I  A LOAD RESTART has occurred.

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/08/2018 
12:25:17.805893".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3503W  The utility has loaded "50000" rows which equals the total count 
specified by the user.

SQL3110N  The utility has completed processing.  "50000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "50000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/08/2018 
12:25:18.056715".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/08/2018 
12:25:18.058314".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/08/2018 
12:25:18.645329".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 50000
Number of rows skipped      = 0
Number of rows loaded       = 50000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 50000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
12:21:30.398408".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL3531I  A LOAD RESTART has occurred.

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
12:26:28.078477".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3503W  The utility has loaded "50000" rows which equals the total count 
specified by the user.

SQL3110N  The utility has completed processing.  "50000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "50000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/26/2018 
12:26:28.324509".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/26/2018 
12:26:28.326088".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/26/2018 
12:26:28.894479".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 50000
Number of rows skipped      = 0
Number of rows loaded       = 50000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 50000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
16:22:01.794599".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL3531I  A LOAD RESTART has occurred.

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
16:24:06.603748".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3503W  The utility has loaded "50000" rows which equals the total count 
specified by the user.

SQL3110N  The utility has completed processing.  "50000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "50000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/26/2018 
16:24:06.858819".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/26/2018 
16:24:06.861813".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/26/2018 
16:24:07.462888".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 50000
Number of rows skipped      = 0
Number of rows loaded       = 50000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 50000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/01/2018 
13:39:43.995062".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL3531I  A LOAD RESTART has occurred.

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/01/2018 
13:42:51.023726".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3503W  The utility has loaded "50000" rows which equals the total count 
specified by the user.

SQL3110N  The utility has completed processing.  "50000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "50000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/01/2018 
13:42:51.315874".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/01/2018 
13:42:51.319935".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/01/2018 
13:42:51.751139".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 50000
Number of rows skipped      = 0
Number of rows loaded       = 50000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 50000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
16:47:22.459257".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL3531I  A LOAD RESTART has occurred.

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
16:48:20.523231".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3503W  The utility has loaded "50000" rows which equals the total count 
specified by the user.

SQL3110N  The utility has completed processing.  "50000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "50000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
16:48:20.842805".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
16:48:20.845787".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
16:48:21.185794".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 50000
Number of rows skipped      = 0
Number of rows loaded       = 50000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 50000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:48:59.699280".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL0289N  Unable to allocate new pages in table space "DMSMTSPD".  
SQLSTATE=57011

SQL3531I  A LOAD RESTART has occurred.

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:49:49.793495".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3503W  The utility has loaded "50000" rows which equals the total count 
specified by the user.

SQL3110N  The utility has completed processing.  "50000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "50000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
20:49:50.174339".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
20:49:50.177642".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
20:49:50.547875".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 50000
Number of rows skipped      = 0
Number of rows loaded       = 50000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 50000

