SQL3109N  The utility is beginning to load data from file 
"/home/inst461/reorg/savehist.del".

SQL2036N  The path for the file, named pipe, or device 
"/home/inst461/reorg/savehist.del" is not valid.

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 0
Number of rows skipped      = 0
Number of rows loaded       = 0
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 0

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/08/2018 
09:44:21.851994".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/08/2018 
09:44:22.367250".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/08/2018 
09:44:22.374457".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/08/2018 
09:44:22.531196".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
12:19:22.275178".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/26/2018 
12:19:22.767651".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/26/2018 
12:19:22.771606".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/26/2018 
12:19:22.963103".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/26/2018 
16:20:25.419157".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/26/2018 
16:20:25.946883".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/26/2018 
16:20:25.952255".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/26/2018 
16:20:26.090791".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/01/2018 
13:37:38.760613".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/01/2018 
13:37:39.444786".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/01/2018 
13:37:39.448177".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/01/2018 
13:37:39.673197".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
16:44:20.186596".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
16:44:20.987429".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
16:44:20.990876".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
16:44:21.158149".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/dmsts/savehist.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:48:01.148584".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "137619" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "137619".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
20:48:01.913252".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
20:48:01.916153".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
20:48:02.072436".


Number of rows read         = 137619
Number of rows skipped      = 0
Number of rows loaded       = 137619
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 137619

