#!/bin/sh
# Licensed Materials - Property of IBM
#
# 5724-E34, 5725-R75
# 
# (c) Copyright IBM Corp. 2012, 2015 All Rights Reserved.
# 
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.

#binDir=`dirname "$0"`
bindir=/software/ibm-datasrvrmgr
dsserver_home="$binDir"/..
cd "${dsserver_home}"
#dsserver_home=`pwd`
dsserver_home=/software/ibm-datasrvrmgr
echo dsserver_home: $dsserver_home
export dsserver_home
JAVA_HOME=${dsserver_home}/java
export JAVA_HOME
PATH=${JAVA_HOME}/java/jre/bin:$PATH
export PATH

if [ -r "${dsserver_home}/bin/precheck.rc" ]
then
. "${dsserver_home}/bin/precheck.rc"
fi

errlevel=0
if [ -f "${dsserver_home}"/logs/nohup.log ]
then
	mv -f "${dsserver_home}"/logs/nohup${DSSERVER_ID}.log "${dsserver_home}"/logs/nohup${DSSERVER_ID}.log.old
	errlevel=$?
fi
if [ ${errlevel} -eq 0 ];
then
	nohup "${dsserver_home}"/bin/server-startup.sh > "${dsserver_home}"/logs/nohup${DSSERVER_ID}.log 2>&1 &
	echo "Starting server dsweb."
	sleep 5
fi

count=`ps -ef | grep ibm-datasrvrmgr | grep status:start|grep -v "grep" | wc -l`

while [ $count -ge 1 ]
do
    sleep 5
    count=`ps -ef | grep ibm-datasrvrmgr | grep status:start|grep -v "grep" | wc -l`
done

line=`ps -ef | grep ibm-datasrvrmgr | grep status:start|grep -v "grep" | wc -l`
if [ $line -eq 0 ];
then 
    echo "DSM SERVER STATUS: ACTIVE"
fi

stty echo

