SELECT HISTORY.BRANCH_ID, 
   TELLER.TELLER_NAME, 
  HISTORY.ACCTNAME, 
  HISTORY.ACCT_ID, 
  HISTORY.BALANCE 
  FROM HISTORY AS HISTORY, 
  TELLER AS TELLER 
  WHERE 
HISTORY.TELLER_ID =TELLER.TELLER_ID
   AND HISTORY.BRANCH_ID =25 
  ORDER BY HISTORY.BRANCH_ID ASC,
 HISTORY.ACCT_ID ASC
