SQL3109N  The utility is beginning to load data from file 
"/home/inst464/bin/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/12/2018 
08:37:45.972434".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL2315N  The RUNSTATS utility was called with the " USE PROFILE" option.  
However, a statistics profile for this table does not exist.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/12/2018 
08:37:46.673796".

SQL3500W  The utility is beginning the "BUILD" phase at time "04/12/2018 
08:37:46.675996".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "04/12/2018 
08:37:46.908324".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/bin/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/12/2018 
08:37:47.770135".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL2315N  The RUNSTATS utility was called with the " USE PROFILE" option.  
However, a statistics profile for this table does not exist.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/12/2018 
08:37:48.396553".

SQL3500W  The utility is beginning the "BUILD" phase at time "04/12/2018 
08:37:48.399007".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "04/12/2018 
08:37:48.603562".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/bin/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/12/2018 
08:38:21.066462".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL2315N  The RUNSTATS utility was called with the " USE PROFILE" option.  
However, a statistics profile for this table does not exist.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/12/2018 
08:38:21.637697".

SQL3500W  The utility is beginning the "BUILD" phase at time "04/12/2018 
08:38:21.640878".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "04/12/2018 
08:38:22.364046".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/bin/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/12/2018 
08:38:23.158914".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL2315N  The RUNSTATS utility was called with the " USE PROFILE" option.  
However, a statistics profile for this table does not exist.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/12/2018 
08:38:23.796011".

SQL3500W  The utility is beginning the "BUILD" phase at time "04/12/2018 
08:38:23.799035".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "04/12/2018 
08:38:24.008871".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/bin/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/03/2018 
13:58:21.303842".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL2315N  The RUNSTATS utility was called with the " USE PROFILE" option.  
However, a statistics profile for this table does not exist.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/03/2018 
13:58:22.092584".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/03/2018 
13:58:22.096420".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/03/2018 
13:58:22.314824".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/bin/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/03/2018 
13:58:23.153387".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL2315N  The RUNSTATS utility was called with the " USE PROFILE" option.  
However, a statistics profile for this table does not exist.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/03/2018 
13:58:23.929344".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/03/2018 
13:58:23.932087".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/03/2018 
13:58:24.150423".

SQL3107W  At least one warning message was encountered during LOAD processing.


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

