SQL3109N  The utility is beginning to load data from file 
"/home/inst464/Db2memory/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/29/2018 
09:18:56.387356".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/29/2018 
09:18:57.364592".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/29/2018 
09:18:57.383591".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/29/2018 
09:18:57.843916".


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/Db2memory/hist200k.del".

SQL3500W  The utility is beginning the "ANALYZE" phase at time "03/29/2018 
09:21:12.317796".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "ANALYZE" phase at time "03/29/2018 
09:21:13.922454".

SQL3500W  The utility is beginning the "LOAD" phase at time "03/29/2018 
09:21:13.924863".

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "03/29/2018 
09:21:15.236434".

SQL3500W  The utility is beginning the "BUILD" phase at time "03/29/2018 
09:21:15.240538".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "03/29/2018 
09:21:15.320197".


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/Db2memory/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/17/2018 
08:38:48.482908".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/17/2018 
08:38:49.616020".

SQL3500W  The utility is beginning the "BUILD" phase at time "04/17/2018 
08:38:49.618637".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "04/17/2018 
08:38:50.177330".


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/Db2memory/hist200k.del".

SQL3500W  The utility is beginning the "ANALYZE" phase at time "04/17/2018 
08:40:37.705139".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "ANALYZE" phase at time "04/17/2018 
08:40:39.449484".

SQL3500W  The utility is beginning the "LOAD" phase at time "04/17/2018 
08:40:39.459006".

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "04/17/2018 
08:40:40.846493".

SQL3500W  The utility is beginning the "BUILD" phase at time "04/17/2018 
08:40:40.849477".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "04/17/2018 
08:40:40.929984".


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/Db2memory/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/03/2018 
06:55:59.943713".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/03/2018 
06:56:01.223432".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/03/2018 
06:56:01.225899".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/03/2018 
06:56:01.735198".


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/Db2memory/hist200k.del".

SQL3500W  The utility is beginning the "ANALYZE" phase at time "05/03/2018 
06:56:36.495615".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "ANALYZE" phase at time "05/03/2018 
06:56:38.615181".

SQL3500W  The utility is beginning the "LOAD" phase at time "05/03/2018 
06:56:38.616218".

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "05/03/2018 
06:56:40.062179".

SQL3500W  The utility is beginning the "BUILD" phase at time "05/03/2018 
06:56:40.064013".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "05/03/2018 
06:56:40.177519".


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/Db2memory/hist200k.del".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:56:49.098212".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
20:56:50.289909".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
20:56:50.292852".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
20:56:50.670065".


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

SQL3109N  The utility is beginning to load data from file 
"/home/inst464/Db2memory/hist200k.del".

SQL3500W  The utility is beginning the "ANALYZE" phase at time "11/27/2020 
20:57:05.221814".

SQL3519W  Begin Load Consistency Point. Input record count = "0".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "ANALYZE" phase at time "11/27/2020 
20:57:07.283694".

SQL3500W  The utility is beginning the "LOAD" phase at time "11/27/2020 
20:57:07.283951".

SQL3110N  The utility has completed processing.  "200000" rows were read from 
the input file.

SQL3519W  Begin Load Consistency Point. Input record count = "200000".

SQL3520W  Load Consistency Point was successful.

SQL3515W  The utility has finished the "LOAD" phase at time "11/27/2020 
20:57:09.585582".

SQL3500W  The utility is beginning the "BUILD" phase at time "11/27/2020 
20:57:09.589356".

SQL3213I  The indexing mode is "REBUILD".

SQL3515W  The utility has finished the "BUILD" phase at time "11/27/2020 
20:57:09.633978".


Number of rows read         = 200000
Number of rows skipped      = 0
Number of rows loaded       = 200000
Number of rows rejected     = 0
Number of rows deleted      = 0
Number of rows committed    = 200000

