-- Create Application tablespaces
CONNECT TO TP1;
-- Create Objects

CREATE TABLESPACE TESTSMALL
    USING STOGROUP TP1SG1 INITIALSIZE 4M
    EXTENTSIZE 4 ;
    
CREATE TABLESPACE TESTHIST1
    MANAGED BY DATABASE USING (FILE '/database/inst464/testhist1' 5000)
    EXTENTSIZE 64 PREFETCHSIZE 64  autoresize yes ;
CREATE TABLESPACE TESTHIST2
    MANAGED BY DATABASE USING (FILE '/database/inst464/testhist2' 5000)
    EXTENTSIZE 64 PREFETCHSIZE 64  autoresize yes ;

CONNECT RESET;
TERMINATE;
