CREATE UNIQUE INDEX ACCTINDX ON ACCT(ACCT_ID) ;

CREATE INDEX HISTIX1 ON HISTORY (BRANCH_ID ASC)
 ALLOW REVERSE SCANS ;

CREATE UNIQUE INDEX BRANINDX ON BRANCH(BRANCH_ID) ;

CREATE UNIQUE INDEX TELLINDX ON TELLER(TELLER_ID) ;
