
CREATE TABLE COLORG.HIST_UMQT ( BRANCH_ID, TELLER_ID, SBALANCE , SCOUNT )
 AS ( SELECT BRANCH_ID, TELLER_ID , SUM(BALANCE) AS SBALANCE, COUNT(*) AS SCOUNT  
 FROM COLORG.HISTORY GROUP BY BRANCH_ID, TELLER_ID ) DATA INITIALLY DEFERRED REFRESH DEFERRED 
 MAINTAINED BY USER ORGANIZE BY COLUMN IN TSCOLD;

SET INTEGRITY FOR COLORG.HIST_UMQT ALL IMMEDIATE UNCHECKED;
