-- <ScriptOptions statementTerminator=";" />
INSERT INTO COLORG.HIST_MQT2 ( SELECT BRANCH_ID, TELLER_ID , SUM(BALANCE) AS SBALANCE, COUNT(*) AS SCOUNT  
 FROM COLORG.HISTORYC GROUP BY BRANCH_ID, TELLER_ID ) ;
